name: Update RSS

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bokuyaba-rss build
        run: |
          version=0.2.0
          wget "https://github.com/naari3/bokuyaba-rss/releases/download/v${version}/bokuyaba-rss_v${version}_x86_64-unknown-linux-musl.zip"
          unzip "bokuyaba-rss_v${version}_x86_64-unknown-linux-musl.zip"
          ./bokuyaba-rss
      - name: mv public
        run: |
          mkdir ./public
          mv ./feed.xml ./public/feed.xml
          mv ./index.html ./public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
